image:
  native: true # Default to the native image
  # name: ghcr.io/drogue-iot/ditto-reconciler # overrides the "native" setting
  # tag: # defaults to the app version
  # pullPolicy: IfNotPresent # defaults to Always for "latest" and IfNotPresent otherwise

replicaCount: 1

kafka:
  bootstrapServers: "localhost:9091"
  topic: ditto-events
  groupId: ditto-reconciler
  properties: { }

drogue:
  api:
    url: https://api.sandbox.drogue.cloud
    username:
    password:

logging:
  level: INFO

imagePullSecrets: [ ]

podSecurityContext: { }

securityContext: { }

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }