kafka:
  bootstrap:
    servers: localhost:9091

mp:
  messaging:
    incoming:
      events:
        connector: smallrye-kafka
        topic: ditto-events
        value:
          deserializer: io.drogue.cloud.ditto.reconciler.model.EventDeserializer

io:
  drogue:
    cloud:
      #command:
      #  client:
      #    username: foo
      #    password: bar
      ditto:
        reconciler:
          command:
            CommandClient/mp-rest/url: https://api.sandbox.drogue.cloud
            CommandClient/mp-rest/scope: javax.inject.Singleton

quarkus:
  ssl:
    native: true
  log:
    level: INFO
  kafka:
    health:
      enabled: true
